
INSERT INTO guidance_workflows (id, workflow_key, title_en, target_role, is_active)
VALUES ('e0b9b3e1-2b1f-4b0e-9b1f-3b0e9b1f3b0e', 'profile_setup', 'Guide to setting up your artisan profile', 'artisan', true)
ON CONFLICT (id) DO UPDATE SET workflow_key = EXCLUDED.workflow_key, title_en = EXCLUDED.title_en, target_role = EXCLUDED.target_role, is_active = EXCLUDED.is_active;

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('e0b9b3e1-2b1f-4b0e-9b1f-3b0e9b1f3b0e', 1, 'Profile Setup', 'profile-name-field', 'point', 'Enter your name', 'உங்கள் பெயரை உள்ளிடவும்', 'अपना नाम दर्ज करें', 'మీ పేరు నమోదు చేయండి', 'ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ', 'നിങ്ങളുടെ പേര് നൽകുക', 'আপনার নাম লিখুন', 'तुमचे नाव प्रविष्ट करा', 'اپنا نام درج کریں', 'Please fill out the name field.', 'பெயர் புலத்தை நிரப்பவும்.', 'कृपया नाम फ़ील्ड भरें।', 'దయచేసి పేరు ఫీల్డ్ పూరించండి.', 'ದಯವಿಟ್ಟು ಹೆಸರು ಕ್ಷೇತ್ರವನ್ನು ಭರ್ತಿ ಮಾಡಿ.', 'ദയവായി പേര് ഫീൽഡ് പൂരിപ്പിക്കുക.', 'দয়া করে নাম ক্ষেত্রটি পূরণ করুন।', 'कृपया नाव फील्ड भरा.', 'براہ کرم نام کا فیلڈ پُر کریں۔');

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('e0b9b3e1-2b1f-4b0e-9b1f-3b0e9b1f3b0e', 2, 'Profile Setup', 'profile-craft-type-dropdown', 'point', 'Select your craft type', 'உங்கள் கைவினை வகையைத் தேர்ந்தெடுக்கவும்', 'अपने शिल्प का प्रकार चुनें', 'మీ క్రాఫ్ట్ రకాన్ని ఎంచుకోండి', 'ನಿಮ್ಮ ಕರಕುಶಲ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ', 'നിങ്ങളുടെ ക്രാഫ്റ്റ് തരം തിരഞ്ഞെടുക്കുക', 'আপনার শিল্পের ধরণ নির্বাচন করুন', 'तुमचा हस्तकला प्रकार निवडा', 'اپنی دستکاری کی قسم منتخب کریں', 'Please select your craft type from the list.', 'பட்டியலில் இருந்து உங்கள் கைவினை வகையைத் தேர்ந்தெடுக்கவும்.', 'कृपया सूची से अपने शिल्प का प्रकार चुनें।', 'దయచేసి జాబితా నుండి మీ క్రాఫ్ట్ రకాన్ని ఎంచుకోండి.', 'ದಯವಿಟ್ಟು ಪಟ್ಟಿಯಿಂದ ನಿಮ್ಮ ಕರಕುಶಲ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ.', 'ലിസ്റ്റിൽ നിന്നും നിങ്ങളുടെ ക്രാഫ്റ്റ് തരം തിരഞ്ഞെടുക്കുക.', 'দয়া করে তালিকা থেকে আপনার শিল্পের ধরণ নির্বাচন করুন।', 'कृपया सूचीतून तुमचा हस्तकला प्रकार निवडा.', 'براہ کرم فہرست سے اپنی دستکاری کی قسم منتخب کریں۔');

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('e0b9b3e1-2b1f-4b0e-9b1f-3b0e9b1f3b0e', 3, 'Profile Setup', 'profile-location-field', 'point', 'Enter your location', 'உங்கள் இருப்பிடத்தை உள்ளிடவும்', 'अपना स्थान दर्ज करें', 'మీ స్థానాన్ని నమోదు చేయండి', 'ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ನಮೂದಿಸಿ', 'നിങ്ങളുടെ സ്ഥലം നൽകുക', 'আপনার অবস্থান লিখুন', 'तुमचे स्थान प्रविष्ट करा', 'اپنا مقام درج کریں', 'Please fill out the location field.', 'இருப்பிட புலத்தை நிரப்பவும்.', 'कृपया स्थान फ़ील्ड भरें।', 'దయచేసి స్థాన ఫీల్డ్ పూరించండి.', 'ದಯವಿಟ್ಟು ಸ್ಥಳ ಕ್ಷೇತ್ರವನ್ನು ಭರ್ತಿ ಮಾಡಿ.', 'ദയവായി സ്ഥല ഫീൽഡ് പൂരിപ്പിക്കുക.', 'দয়া করে অবস্থান ক্ষেত্রটি পূরণ করুন।', 'कृपया स्थान फील्ड भरा.', 'براہ کرم مقام کا فیلڈ پُر کریں۔');

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('e0b9b3e1-2b1f-4b0e-9b1f-3b0e9b1f3b0e', 4, 'Profile Setup', 'profile-story-textarea', 'point', 'Tell your craft story', 'உங்கள் கைவினை கதையை சொல்லுங்கள்', 'अपनी शिल्प कहानी बताएं', 'మీ క్రాఫ్ట్ కథను చెప్పండి', 'ನಿಮ್ಮ ಕರಕುಶಲ ಕಥೆಯನ್ನು ಹೇಳಿ', 'നിങ്ങളുടെ ക്രാഫ്റ്റ് കഥ പറയുക', 'আপনার শিল্পের গল্প বলুন', 'तुमची हस्तकलेची कथा सांगा', 'اپنی دستکاری کی کہانی سنائیں', 'Please fill out your craft story.', 'உங்கள் கைவினை கதையை நிரப்பவும்.', 'कृपया अपनी शिल्प कहानी भरें।', 'దయచేసి మీ క్రాఫ్ట్ కథను పూరించండి.', 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಕರಕುಶಲ ಕಥೆಯನ್ನು ಭರ್ತಿ ಮಾಡಿ.', 'ദയവായി നിങ്ങളുടെ ക്രാഫ്റ്റ് കഥ പൂരിപ്പിക്കുക.', 'দয়া করে আপনার শিল্পের গল্প পূরণ করুন।', 'कृपया तुमची हस्तकलेची कथा भरा.', 'براہ کرم اپنی دستکاری کی کہانی پُر کریں۔');

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('e0b9b3e1-2b1f-4b0e-9b1f-3b0e9b1f3b0e', 5, 'Profile Setup', 'profile-photo-upload', 'point', 'Add your profile photo', 'உங்கள் சுயவிவரப் புகைப்படத்தைச் சேர்க்கவும்', 'अपनी प्रोफ़ाइल फ़ोटो जोड़ें', 'మీ ప్రొఫైల్ ఫోటోను జోడించండి', 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಫೋಟೋ ಸೇರಿಸಿ', 'നിങ്ങളുടെ പ്രൊഫൈൽ ഫോട്ടോ ചേർക്കുക', 'আপনার প্রোফাইল ফটো যোগ করুন', 'तुमचा प्रोफाइल फोटो जोडा', 'اپنی پروفائل تصویر شامل کریں', 'Please upload a profile photo.', 'சுயவிவரப் புகைப்படத்தைப் பதிவேற்றவும்.', 'कृपया एक प्रोफ़ाइल फ़ोटो अपलोड करें।', 'దయచేసి ప్రొఫైల్ ఫోటోను అప్‌లోడ్ చేయండి.', 'ದಯವಿಟ್ಟು ಪ್ರೊಫೈಲ್ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.', 'ദയവായി ഒരു പ്രൊഫൈൽ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക.', 'দয়া করে একটি প্রোফাইল ফটো আপলোড করুন।', 'कृपया प्रोफाइल फोटो अपलोड करा.', 'براہ کرم ایک پروفائل تصویر اپ لوڈ کریں۔');

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('e0b9b3e1-2b1f-4b0e-9b1f-3b0e9b1f3b0e', 6, 'Profile Setup', 'profile-save-button', 'point', 'Save your profile', 'உங்கள் சுயவிவரத்தை சேமிக்கவும்', 'अपनी प्रोफ़ाइल सहेजें', 'మీ ప్రొఫైల్‌ను సేవ్ చేయండి', 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಉಳಿಸಿ', 'നിങ്ങളുടെ പ്രൊഫൈൽ സംരക്ഷിക്കുക', 'আপনার প্রোফাইল সংরক্ষণ করুন', 'तुमचा प्रोफाइल जतन करा', 'اپنی پروفائل محفوظ کریں', 'Click the button to save your profile.', 'உங்கள் சுயவிவரத்தை சேமிக்க பொத்தானைக் கிளிக் செய்யவும்.', 'अपनी प्रोफ़ाइल सहेजने के लिए बटन पर क्लिक करें।', 'మీ ప్రొఫైల్‌ను సేవ్ చేయడానికి బటన్‌పై క్లిక్ చేయండి.', 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಉಳಿಸಲು ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ.', 'നിങ്ങളുടെ പ്രൊഫൈൽ സംരക്ഷിക്കാൻ ബട്ടണിൽ ക്ലിക്കുചെയ്യുക.', 'আপনার প্রোফাইল সংরক্ষণ করতে বোতামটিতে ক্লিক করুন।', 'तुमचा प्रोफाइल जतन करण्यासाठी बटणावर क्लिक करा.', 'اپنی پروفائل محفوظ کرنے کے لیے بٹن پر کلک کریں۔');

INSERT INTO guidance_workflows (id, workflow_key, title_en, target_role, is_active)
VALUES ('f1c8d2f1-3c2f-4c1e-ac2f-4c1fac2f4c1f', 'first_product_upload', 'Guide to uploading your first product', 'artisan', true)
ON CONFLICT (id) DO UPDATE SET workflow_key = EXCLUDED.workflow_key, title_en = EXCLUDED.title_en, target_role = EXCLUDED.target_role, is_active = EXCLUDED.is_active;

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('f1c8d2f1-3c2f-4c1e-ac2f-4c1fac2f4c1f', 1, 'Dashboard', 'add-product-button', 'tap', 'Tap here to add your first product', 'உங்கள் முதல் தயாரிப்பைச் சேர்க்க இங்கே தட்டவும்', 'अपना पहला उत्पाद जोड़ने के लिए यहां टैप करें', 'మీ మొదటి ఉత్పత్తిని జోడించడానికి ఇక్కడ నొక్కండి', 'ನಿಮ್ಮ ಮೊದಲ ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಲು ಇಲ್ಲಿ ಟ್ಯಾಪ್ ಮಾಡಿ', 'നിങ്ങളുടെ ആദ്യ ഉൽപ്പന്നം ചേർക്കാൻ ഇവിടെ ടാപ്പുചെയ്യുക', 'আপনার প্রথম পণ্য যোগ করতে এখানে আলতো চাপুন', 'तुमचे पहिले उत्पादन जोडण्यासाठी येथे टॅप करा', 'اپنی پہلی پروڈکٹ شامل کرنے کے لیے یہاں ٹیپ کریں', 'Please click the Add Product button.', 'தயாரிப்பைச் சேர் பொத்தானைக் கிளிக் செய்யவும்.', 'कृपया उत्पाद जोड़ें बटन पर क्लिक करें।', 'దయచేసి ఉత్పత్తిని జోడించు బటన్‌పై క్లిక్ చేయండి.', 'ದಯವಿಟ್ಟು ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಿ ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ.', 'ദയവായി ഉൽപ്പന്നം ചേർക്കുക ബട്ടണിൽ ക്ലിക്കുചെയ്യുക.', 'দয়া করে পণ্য যোগ করুন বোতামটিতে ক্লিক করুন।', 'कृपया उत्पादन जोडा बटणावर क्लिक करा.', 'براہ کرم پروڈکٹ شامل کریں بٹن پر کلک کریں۔');

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('f1c8d2f1-3c2f-4c1e-ac2f-4c1fac2f4c1f', 2, 'Product Step 1', 'add-photo-button', 'tap', 'Add a clear photo of your product', 'உங்கள் தயாரிப்பின் தெளிவான புகைப்படத்தைச் சேர்க்கவும்', 'अपने उत्पाद की एक स्पष्ट तस्वीर जोड़ें', 'మీ ఉత్పత్తి యొక్క స్పష్టమైన ఫోటోను జోడించండి', 'ನಿಮ್ಮ ಉತ್ಪನ್ನದ ಸ್ಪಷ್ಟ ಫೋಟೋವನ್ನು ಸೇರಿಸಿ', 'നിങ്ങളുടെ ഉൽപ്പന്നത്തിന്റെ വ്യക്തമായ ഫോട്ടോ ചേർക്കുക', 'আপনার পণ্যের একটি পরিষ্কার ছবি যোগ করুন', 'तुमच्या उत्पादनाचा स्पष्ट फोटो जोडा', 'اپنی پروڈکٹ کی ایک واضح تصویر شامل کریں', 'Upload a product photo to proceed.', 'தொடர தயாரிப்பு புகைப்படத்தைப் பதிவேற்றவும்.', 'आगे बढ़ने के लिए उत्पाद फ़ोटो अपलोड करें।', 'కొనసాగడానికి ఉత్పత్తి ఫోటోను అప్‌లోడ్ చేయండి.', 'ಮುಂದುವರಿಯಲು ಉತ್ಪನ್ನದ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.', 'തുടരുന്നതിന് ഉൽപ്പന്ന ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക.', 'এগিয়ে যেতে পণ্যের একটি ছবি আপলোড করুন।', 'पुढे जाण्यासाठी उत्पादनाचा फोटो अपलोड करा.', 'آگے بڑھنے کے لیے پروڈکٹ کی تصویر اپ لوڈ کریں۔');

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('f1c8d2f1-3c2f-4c1e-ac2f-4c1fac2f4c1f', 3, 'Product Step 1 Loading', 'image-processing-loader', 'wait', 'Please wait, we are improving your photo', 'தயவுசெய்து காத்திருக்கவும், உங்கள் புகைப்படத்தை மேம்படுத்துகிறோம்', 'कृपया प्रतीक्षा करें, हम आपकी फ़ोटो को बेहतर बना रहे हैं', 'దయచేసి వేచి ఉండండి, మేము మీ ఫోటోను మెరుగుపరుస్తున్నాము', 'ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ, ನಾವು ನಿಮ್ಮ ಫೋಟೋವನ್ನು ಸುಧಾರಿಸುತ್ತಿದ್ದೇವೆ', 'ദയവായി കാത്തിരിക്കുക, ഞങ്ങൾ നിങ്ങളുടെ ഫോട്ടോ മെച്ചപ്പെടുത്തുകയാണ്', 'অনুগ্রহ করে অপেক্ষা করুন, আমরা আপনার ছবি উন্নত করছি', 'कृपया प्रतीक्षा करा, आम्ही तुमचा फोटो सुधारत आहोत', 'براہ کرم انتظار کریں، ہم آپ کی تصویر کو بہتر بنا رہے ہیں', 'Processing photo...', 'புகைப்படத்தை செயலாக்குகிறது...', 'फ़ोटो प्रोसेस हो रही है...', 'ఫోటో ప్రాసెస్ చేయబడుతోంది...', 'ಫೋಟೋ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...', 'ഫോട്ടോ പ്രോസസ്സ് ചെയ്യുന്നു...', 'ছবি প্রক্রিয়া করা হচ্ছে...', 'फोटोवर प्रक्रिया होत आहे...', 'تصویر پر کارروائی ہو رہی ہے...');

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('f1c8d2f1-3c2f-4c1e-ac2f-4c1fac2f4c1f', 4, 'Product Step 2 Voice', 'record-voice-button', 'tap', 'Describe your product in your language', 'உங்கள் தயாரிப்பை உங்கள் மொழியில் விவரிக்கவும்', 'अपनी भाषा में अपने उत्पाद का वर्णन करें', 'మీ ఉత్పత్తిని మీ భాషలో వివరించండి', 'ನಿಮ್ಮ ಉತ್ಪನ್ನವನ್ನು ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ವಿವರಿಸಿ', 'നിങ്ങളുടെ ഉൽപ്പന്നത്തെ നിങ്ങളുടെ ഭാഷയിൽ വിവരിക്കുക', 'আপনার ভাষায় আপনার পণ্যের বর্ণনা দিন', 'तुमच्या भाषेत तुमच्या उत्पादनाचे वर्णन करा', 'اپنی زبان میں اپنی پروڈکٹ کی وضاحت کریں', 'Record or type your product description.', 'உங்கள் தயாரிப்பு விளக்கத்தை பதிவு செய்யவும் அல்லது தட்டச்சு செய்யவும்.', 'अपने उत्पाद का विवरण रिकॉर्ड करें या टाइप करें।', 'మీ ఉత్పత్తి వివరణను రికార్డ్ చేయండి లేదా టైప్ చేయండి.', 'ನಿಮ್ಮ ಉತ್ಪನ್ನದ ವಿವರಣೆಯನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಿ ಅಥವಾ ಟೈಪ್ ಮಾಡಿ.', 'നിങ്ങളുടെ ഉൽപ്പന്ന വിവരണം റെക്കോർഡ് ചെയ്യുക അല്ലെങ്കിൽ ടൈപ്പ് ചെയ്യുക.', 'আপনার পণ্যের বিবরণ রেকর্ড করুন বা টাইপ করুন।', 'तुमच्या उत्पादनाचे वर्णन रेकॉर्ड करा किंवा टाइप करा.', 'اپنی پروڈکٹ کی تفصیل ریکارڈ کریں یا ٹائپ کریں۔');

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('f1c8d2f1-3c2f-4c1e-ac2f-4c1fac2f4c1f', 5, 'Product Step 2 Loading', 'ai-processing-loader', 'wait', 'Creating your product details...', 'உங்கள் தயாரிப்பு விவரங்களை உருவாக்குகிறது...', 'आपके उत्पाद का विवरण बना रहा है...', 'మీ ఉత్పత్తి వివరాలను సృష్టిస్తోంది...', 'ನಿಮ್ಮ ಉತ್ಪನ್ನದ ವಿವರಗಳನ್ನು ರಚಿಸಲಾಗುತ್ತಿದೆ...', 'നിങ്ങളുടെ ഉൽപ്പന്ന വിവരങ്ങൾ സൃഷ്ടിക്കുന്നു...', 'আপনার পণ্যের বিবরণ তৈরি করা হচ্ছে...', 'तुमच्या उत्पादनाचे तपशील तयार करत आहे...', 'آپ کی پروڈکٹ کی تفصیلات بنا رہا ہے...', 'Processing details...', 'விவரங்களை செயலாக்குகிறது...', 'विवरण प्रोसेस हो रहे हैं...', 'వివరాలను ప్రాసెస్ చేస్తోంది...', 'ವಿವರಗಳನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...', 'വിവരങ്ങൾ പ്രോസസ്സ് ചെയ്യുന്നു...', 'বিবরণ প্রক্রিয়া করা হচ্ছে...', 'तपशील प्रक्रिया होत आहे...', 'تفصیلات پر کارروائی ہو رہی ہے...');

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('f1c8d2f1-3c2f-4c1e-ac2f-4c1fac2f4c1f', 6, 'Product Step 3 Review AI', 'review-section', 'point', 'Check and edit your product details', 'உங்கள் தயாரிப்பு விவரங்களைச் சரிபார்த்து திருத்தவும்', 'अपने उत्पाद विवरण की जाँच करें और संपादित करें', 'మీ ఉత్పత్తి వివరాలను తనిఖీ చేయండి మరియు సవరించండి', 'ನಿಮ್ಮ ಉತ್ಪನ್ನದ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸಂಪಾದಿಸಿ', 'നിങ്ങളുടെ ഉൽപ്പന്ന വിവരങ്ങൾ പരിശോധിക്കുകയും തിരുത്തുകയും ചെയ്യുക', 'আপনার পণ্যের বিবরণ পরীক্ষা করুন এবং সম্পাদনা করুন', 'तुमच्या उत्पादनाचे तपशील तपासा आणि संपादित करा', 'اپنی پروڈکٹ کی تفصیلات چیک کریں اور ان میں ترمیم کریں', 'Please review your product details.', 'உங்கள் தயாரிப்பு விவரங்களை மதிப்பாய்வு செய்யவும்.', 'कृपया अपने उत्पाद विवरण की समीक्षा करें।', 'దయచేసి మీ ఉత్పత్తి వివరాలను సమీక్షించండి.', 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಉತ್ಪನ್ನದ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.', 'ദയവായി നിങ്ങളുടെ ഉൽപ്പന്ന വിവരങ്ങൾ അവലോകനം ചെയ്യുക.', 'দয়া করে আপনার পণ্যের বিবরণ পর্যালোচনা করুন।', 'कृपया तुमच्या उत्पादनाच्या तपशीलांचे पुनरावलोकन करा.', 'براہ کرم اپنی پروڈکٹ کی تفصیلات کا جائزہ لیں۔');

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('f1c8d2f1-3c2f-4c1e-ac2f-4c1fac2f4c1f', 7, 'Product Step 4 Materials', 'material-checklist', 'point', 'Confirm your materials and costs', 'உங்கள் பொருட்கள் மற்றும் செலவுகளை உறுதிப்படுத்தவும்', 'अपनी सामग्री और लागत की पुष्टि करें', 'మీ పదార్థాలు మరియు ఖర్చులను నిర్ధారించండి', 'ನಿಮ್ಮ ಸಾಮಗ್ರಿಗಳು ಮತ್ತು ವೆಚ್ಚಗಳನ್ನು ದೃಢೀಕರಿಸಿ', 'നിങ്ങളുടെ വസ്തുക്കളും ചെലവുകളും സ്ഥിരീകരിക്കുക', 'আপনার উপকরণ এবং খরচ নিশ্চিত করুন', 'तुमची सामग्री आणि खर्चाची पुष्टी करा', 'اپنے مواد اور اخراجات کی تصدیق کریں', 'Review the materials list.', 'பொருட்கள் பட்டியலை மதிப்பாய்வு செய்யவும்.', 'सामग्री सूची की समीक्षा करें।', 'పదార్థాల జాబితాను సమీక్షించండి.', 'ಸಾಮಗ್ರಿಗಳ ಪಟ್ಟಿಯನ್ನು ಪರಿಶೀಲಿಸಿ.', 'വസ്തുക്കളുടെ ലിസ്റ്റ് അവലോകനം ചെയ്യുക.', 'উপকরণের তালিকাটি পর্যালোচনা করুন।', 'सामग्री सूचीचे पुनरावलोकन करा.', 'مواد کی فہرست کا جائزہ لیں۔');

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('f1c8d2f1-3c2f-4c1e-ac2f-4c1fac2f4c1f', 8, 'Product Step 5 Pricing', 'fair-price-section', 'point', 'Set a fair price for your product', 'உங்கள் தயாரிப்புக்கு நியாயமான விலையை நிர்ணயிக்கவும்', 'अपने उत्पाद के लिए एक उचित मूल्य निर्धारित करें', 'మీ ఉత్పత్తికి సరసమైన ధరను నిర్ణయించండి', 'ನಿಮ್ಮ ಉತ್ಪನ್ನಕ್ಕೆ ನ್ಯಾಯಯುತ ಬೆಲೆಯನ್ನು ನಿಗದಿಪಡಿಸಿ', 'നിങ്ങളുടെ ഉൽപ്പന്നത്തിന് ന്യായമായ വില നിശ്ചയിക്കുക', 'আপনার পণ্যের জন্য একটি ন্যায্য মূল্য নির্ধারণ করুন', 'तुमच्या उत्पादनासाठी योग्य किंमत सेट करा', 'اپنی پروڈکٹ کے لیے مناسب قیمت مقرر کریں', 'Set your final product price.', 'உங்கள் இறுதி தயாரிப்பு விலையை அமைக்கவும்.', 'अपना अंतिम उत्पाद मूल्य निर्धारित करें।', 'మీ తుది ఉత్పత్తి ధరను సెట్ చేయండి.', 'ನಿಮ್ಮ ಅಂತಿಮ ಉತ್ಪನ್ನದ ಬೆಲೆಯನ್ನು ಹೊಂದಿಸಿ.', 'നിങ്ങളുടെ അവസാന ഉൽപ്പന്ന വില സജ്ജമാക്കുക.', 'আপনার চূড়ান্ত পণ্যের মূল্য নির্ধারণ করুন।', 'तुमची अंतिम उत्पादनाची किंमत सेट करा.', 'اپنی حتمی پروڈکٹ کی قیمت مقرر کریں۔');

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('f1c8d2f1-3c2f-4c1e-ac2f-4c1fac2f4c1f', 9, 'Product Step 6 Publish', 'readiness-score', 'point', 'Check if your listing is complete', 'உங்கள் பட்டியல் முழுமையாக உள்ளதா எனச் சரிபார்க்கவும்', 'जांचें कि क्या आपकी लिस्टिंग पूरी हो गई है', 'మీ జాబితా పూర్తయిందో లేదో తనిఖీ చేయండి', 'ನಿಮ್ಮ ಪಟ್ಟಿ ಪೂರ್ಣಗೊಂಡಿದೆಯೇ ಎಂದು ಪರಿಶೀಲಿಸಿ', 'നിങ്ങളുടെ ലിസ്റ്റിംഗ് പൂർണ്ണമാണോ എന്ന് പരിശോധിക്കുക', 'আপনার তালিকাটি সম্পূর্ণ হয়েছে কিনা তা পরীক্ষা করুন', 'तुमची सूची पूर्ण झाली आहे का ते तपासा', 'چیک کریں کہ آیا آپ کی فہرست مکمل ہے', 'Review your readiness score.', 'உங்கள் தயார்நிலை மதிப்பெண்ணை மதிப்பாய்வு செய்யவும்.', 'अपने तत्परता स्कोर की समीक्षा करें।', 'మీ సంసిద్ధత స్కోర్‌ను సమీక్షించండి.', 'ನಿಮ್ಮ ಸಿದ್ಧತೆ ಸ್ಕೋರ್ ಅನ್ನು ಪರಿಶೀಲಿಸಿ.', 'നിങ്ങളുടെ തയ്യാറെടുപ്പ് സ്കോർ അവലോകനം ചെയ്യുക.', 'আপনার প্রস্তুতির স্কোর পর্যালোচনা করুন।', 'तुमच्या तयारीच्या स्कोअरचे पुनरावलोकन करा.', 'اپنی تیاری کے اسکور کا جائزہ لیں۔');

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('f1c8d2f1-3c2f-4c1e-ac2f-4c1fac2f4c1f', 10, 'Product Step 6 Publish', 'publish-button', 'tap', 'Publish your product for buyers', 'வாங்குபவர்களுக்காக உங்கள் தயாரிப்பை வெளியிடவும்', 'खरीदारों के लिए अपना उत्पाद प्रकाशित करें', 'కొనుగోలుదారుల కోసం మీ ఉత్పత్తిని ప్రచురించండి', 'ಖರೀದಿದಾರರಿಗಾಗಿ ನಿಮ್ಮ ಉತ್ಪನ್ನವನ್ನು ಪ್ರಕಟಿಸಿ', 'വാങ്ങുന്നവർക്കായി നിങ്ങളുടെ ഉൽപ്പന്നം പ്രസിദ്ധീകരിക്കുക', 'ক্রেতাদের জন্য আপনার পণ্য প্রকাশ করুন', 'खरेदीदारांसाठी तुमचे उत्पादन प्रकाशित करा', 'خریداروں کے لیے اپنی پروڈکٹ شائع کریں', 'Click publish to finish.', 'முடிக்க வெளியிடு என்பதைக் கிளிக் செய்யவும்.', 'समाप्त करने के लिए प्रकाशित करें पर क्लिक करें।', 'పూర్తి చేయడానికి ప్రచురించుపై క్లిక్ చేయండి.', 'ಮುಗಿಸಲು ಪ್ರಕಟಿಸು ಕ್ಲಿಕ್ ಮಾಡಿ.', 'പൂർത്തിയാക്കാൻ പ്രസിദ്ധീകരിക്കുക ക്ലിക്കുചെയ്യുക.', 'শেষ করতে প্রকাশ করুন এ ক্লিক করুন।', 'पूर्ण करण्यासाठी प्रकाशित करा वर क्लिक करा.', 'ختم کرنے کے لیے شائع کریں پر کلک کریں۔');

INSERT INTO guidance_workflows (id, workflow_key, title_en, target_role, is_active)
VALUES ('e3a1b2c4-5d6e-7f8g-9h0i-1j2k3l4m5n6o', 'enquiry_response', 'Guide to responding to a buyer enquiry', 'artisan', true)
ON CONFLICT (id) DO UPDATE SET workflow_key = EXCLUDED.workflow_key, title_en = EXCLUDED.title_en, target_role = EXCLUDED.target_role, is_active = EXCLUDED.is_active;

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('e3a1b2c4-5d6e-7f8g-9h0i-1j2k3l4m5n6o', 1, 'Enquiry List', 'enquiry-list', 'point', 'A buyer is interested in your product', 'ஒரு வாங்குபவர் உங்கள் தயாரிப்பில் ஆர்வம் காட்டுகிறார்', 'एक खरीदार आपके उत्पाद में रुचि रखता है', 'కొనుగోలుదారు మీ ఉత్పత్తిపై ఆసక్తి చూపుతున్నాడు', 'ಖರೀದಿದಾರರು ನಿಮ್ಮ ಉತ್ಪನ್ನದಲ್ಲಿ ಆಸಕ್ತಿ ಹೊಂದಿದ್ದಾರೆ', 'ഒരു വാങ്ങലുകാരൻ നിങ്ങളുടെ ഉൽപ്പന്നത്തിൽ താൽപ്പര്യം പ്രകടിപ്പിക്കുന്നു', 'একজন ক্রেতা আপনার পণ্যে আগ্রহী', 'एक खरेदीदार तुमच्या उत्पादनात स्वारस्य दाखवत आहे', 'ایک خریدار آپ کی پروڈکٹ میں دلچسپی رکھتا ہے', 'You have a new enquiry.', 'உங்களுக்கு ஒரு புதிய விசாரணை உள்ளது.', 'आपके पास एक नई पूछताछ है।', 'మీకు కొత్త విచారణ ఉంది.', 'ನೀವು ಹೊಸ ವಿಚಾರಣೆಯನ್ನು ಹೊಂದಿದ್ದೀರಿ.', 'നിങ്ങൾക്ക് ഒരു പുതിയ അന്വേഷണമുണ്ട്.', 'আপনার একটি নতুন অনুসন্ধান আছে।', 'तुमच्याकडे नवीन चौकशी आहे.', 'آپ کے پاس ایک نئی انکوائری ہے۔');

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('e3a1b2c4-5d6e-7f8g-9h0i-1j2k3l4m5n6o', 2, 'Enquiry Detail', 'enquiry-detail', 'point', 'Review the buyer''s request', 'வாங்குபவரின் கோரிக்கையை மதிப்பாய்வு செய்யவும்', 'खरीदार के अनुरोध की समीक्षा करें', 'కొనుగోలుదారు అభ్యర్థనను సమీక్షించండి', 'ಖರೀದಿದಾರರ ವಿನಂತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ', 'വാങ്ങുന്നയാളുടെ അഭ്യർത്ഥന അവലോകനം ചെയ്യുക', 'ক্রেতার অনুরোধ পর্যালোচনা করুন', 'खरेदीदाराच्या विनंतीचे पुनरावलोकन करा', 'خریدار کی درخواست کا جائزہ لیں', 'Check the details of the enquiry.', 'விசாரணையின் விவரங்களைச் சரிபார்க்கவும்.', 'पूछताछ के विवरण की जांच करें।', 'విచారణ వివరాలను తనిఖీ చేయండి.', 'ವಿಚಾರಣೆಯ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.', 'അന്വേഷണത്തിന്റെ വിശദാംശങ്ങൾ പരിശോധിക്കുക.', 'অনুসন্ধানের বিবরণ পরীক্ষা করুন।', 'चौकशीचे तपशील तपासा.', 'انکوائری کی تفصیلات چیک کریں۔');

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('e3a1b2c4-5d6e-7f8g-9h0i-1j2k3l4m5n6o', 3, 'Enquiry Detail', 'response-options', 'point', 'Choose your response', 'உங்கள் பதிலை தேர்வு செய்யவும்', 'अपनी प्रतिक्रिया चुनें', 'మీ ప్రతిస్పందనను ఎంచుకోండి', 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಆರಿಸಿ', 'നിങ്ങളുടെ പ്രതികരണം തിരഞ്ഞെടുക്കുക', 'আপনার প্রতিক্রিয়া চয়ন করুন', 'तुमचा प्रतिसाद निवडा', 'اپنا جواب منتخب کریں', 'Select how you want to respond.', 'நீங்கள் எவ்வாறு பதிலளிக்க விரும்புகிறீர்கள் என்பதைத் தேர்ந்தெடுக்கவும்.', 'चुनें कि आप कैसे प्रतिक्रिया देना चाहते हैं।', 'మీరు ఎలా ప్రతిస్పందించాలనుకుంటున్నారో ఎంచుకోండి.', 'ನೀವು ಹೇಗೆ ಪ್ರತಿಕ್ರಿಯಿಸಲು ಬಯಸುತ್ತೀರಿ ಎಂಬುದನ್ನು ಆಯ್ಕೆಮಾಡಿ.', 'നിങ്ങൾ എങ്ങനെ പ്രതികരിക്കണമെന്ന് തിരഞ്ഞെടുക്കുക.', 'আপনি কীভাবে সাড়া দিতে চান তা নির্বাচন করুন।', 'तुम्हाला कसा प्रतिसाद द्यायचा आहे ते निवडा.', 'منتخب کریں کہ آپ کیسے جواب دینا چاہتے ہیں۔');

INSERT INTO guidance_steps (workflow_id, step_order, screen_name, target_id, gesture_type, instruction_en, instruction_ta, instruction_hi, instruction_te, instruction_kn, instruction_ml, instruction_bn, instruction_mr, instruction_ur, fallback_instruction_en, fallback_instruction_ta, fallback_instruction_hi, fallback_instruction_te, fallback_instruction_kn, fallback_instruction_ml, fallback_instruction_bn, fallback_instruction_mr, fallback_instruction_ur)
VALUES ('e3a1b2c4-5d6e-7f8g-9h0i-1j2k3l4m5n6o', 4, 'Enquiry Detail', 'send-response-button', 'tap', 'Send your response to the buyer', 'வாங்குபவருக்கு உங்கள் பதிலை அனுப்பவும்', 'खरीदार को अपनी प्रतिक्रिया भेजें', 'కొనుగోలుదారుకు మీ ప్రతిస్పందనను పంపండి', 'ಖರೀದಿದಾರರಿಗೆ ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಕಳುಹಿಸಿ', 'വാങ്ങുന്നയാൾക്ക് നിങ്ങളുടെ പ്രതികരണം അയയ്ക്കുക', 'ক্রেতার কাছে আপনার প্রতিক্রিয়া পাঠান', 'खरेदीदाराला तुमचा प्रतिसाद पाठवा', 'خریدار کو اپنا جواب بھیجیں', 'Click here to send.', 'அனுப்ப இங்கே கிளிக் செய்யவும்.', 'भेजने के लिए यहां क्लिक करें।', 'పంపడానికి ఇక్కడ క్లిక్ చేయండి.', 'ಕಳುಹಿಸಲು ಇಲ್ಲಿ ಕ್ಲಿಕ್ ಮಾಡಿ.', 'അയയ്ക്കാൻ ഇവിടെ ക്ലിക്കുചെയ്യുക.', 'পাঠাতে এখানে ক্লিক করুন।', 'पाठवण्यासाठी येथे क्लिक करा.', 'بھیجنے کے لیے یہاں کلک کریں۔');
