WORKFLOWS = [
    {
        "id": "e0b9b3e1-2b1f-4b0e-9b1f-3b0e9b1f3b0e", # UUIDs
        "name": "profile_setup",
        "description": "Guide to setting up your artisan profile",
        "target_role": "artisan",
        "is_active": True,
        "steps": [
            {
                "step_order": 1,
                "screen_name": "Profile Setup",
                "target_id": "profile-name-field",
                "gesture_type": "point",
                "instruction_en": "Enter your name",
                "instruction_ta": "உங்கள் பெயரை உள்ளிடவும்",
                "instruction_hi": "अपना नाम दर्ज करें",
                "instruction_te": "మీ పేరు నమోదు చేయండి",
                "instruction_kn": "ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
                "instruction_ml": "നിങ്ങളുടെ പേര് നൽകുക",
                "instruction_bn": "আপনার নাম লিখুন",
                "instruction_mr": "तुमचे नाव प्रविष्ट करा",
                "instruction_ur": "اپنا نام درج کریں",
                "fallback_instruction_en": "Please fill out the name field.",
                "fallback_instruction_ta": "பெயர் புலத்தை நிரப்பவும்.",
                "fallback_instruction_hi": "कृपया नाम फ़ील्ड भरें।",
                "fallback_instruction_te": "దయచేసి పేరు ఫీల్డ్ పూరించండి.",
                "fallback_instruction_kn": "ದಯವಿಟ್ಟು ಹೆಸರು ಕ್ಷೇತ್ರವನ್ನು ಭರ್ತಿ ಮಾಡಿ.",
                "fallback_instruction_ml": "ദയവായി പേര് ഫീൽഡ് പൂരിപ്പിക്കുക.",
                "fallback_instruction_bn": "দয়া করে নাম ক্ষেত্রটি পূরণ করুন।",
                "fallback_instruction_mr": "कृपया नाव फील्ड भरा.",
                "fallback_instruction_ur": "براہ کرم نام کا فیلڈ پُر کریں۔"
            },
            {
                "step_order": 2,
                "screen_name": "Profile Setup",
                "target_id": "profile-craft-type-dropdown",
                "gesture_type": "point",
                "instruction_en": "Select your craft type",
                "instruction_ta": "உங்கள் கைவினை வகையைத் தேர்ந்தெடுக்கவும்",
                "instruction_hi": "अपने शिल्प का प्रकार चुनें",
                "instruction_te": "మీ క్రాఫ్ట్ రకాన్ని ఎంచుకోండి",
                "instruction_kn": "ನಿಮ್ಮ ಕರಕುಶಲ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
                "instruction_ml": "നിങ്ങളുടെ ക്രാഫ്റ്റ് തരം തിരഞ്ഞെടുക്കുക",
                "instruction_bn": "আপনার শিল্পের ধরণ নির্বাচন করুন",
                "instruction_mr": "तुमचा हस्तकला प्रकार निवडा",
                "instruction_ur": "اپنی دستکاری کی قسم منتخب کریں",
                "fallback_instruction_en": "Please select your craft type from the list.",
                "fallback_instruction_ta": "பட்டியலில் இருந்து உங்கள் கைவினை வகையைத் தேர்ந்தெடுக்கவும்.",
                "fallback_instruction_hi": "कृपया सूची से अपने शिल्प का प्रकार चुनें।",
                "fallback_instruction_te": "దయచేసి జాబితా నుండి మీ క్రాఫ్ట్ రకాన్ని ఎంచుకోండి.",
                "fallback_instruction_kn": "ದಯವಿಟ್ಟು ಪಟ್ಟಿಯಿಂದ ನಿಮ್ಮ ಕರಕುಶಲ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
                "fallback_instruction_ml": "ലിസ്റ്റിൽ നിന്നും നിങ്ങളുടെ ക്രാഫ്റ്റ് തരം തിരഞ്ഞെടുക്കുക.",
                "fallback_instruction_bn": "দয়া করে তালিকা থেকে আপনার শিল্পের ধরণ নির্বাচন করুন।",
                "fallback_instruction_mr": "कृपया सूचीतून तुमचा हस्तकला प्रकार निवडा.",
                "fallback_instruction_ur": "براہ کرم فہرست سے اپنی دستکاری کی قسم منتخب کریں۔"
            },
            {
                "step_order": 3,
                "screen_name": "Profile Setup",
                "target_id": "profile-location-field",
                "gesture_type": "point",
                "instruction_en": "Enter your location",
                "instruction_ta": "உங்கள் இருப்பிடத்தை உள்ளிடவும்",
                "instruction_hi": "अपना स्थान दर्ज करें",
                "instruction_te": "మీ స్థానాన్ని నమోదు చేయండి",
                "instruction_kn": "ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ನಮೂದಿಸಿ",
                "instruction_ml": "നിങ്ങളുടെ സ്ഥലം നൽകുക",
                "instruction_bn": "আপনার অবস্থান লিখুন",
                "instruction_mr": "तुमचे स्थान प्रविष्ट करा",
                "instruction_ur": "اپنا مقام درج کریں",
                "fallback_instruction_en": "Please fill out the location field.",
                "fallback_instruction_ta": "இருப்பிட புலத்தை நிரப்பவும்.",
                "fallback_instruction_hi": "कृपया स्थान फ़ील्ड भरें।",
                "fallback_instruction_te": "దయచేసి స్థాన ఫీల్డ్ పూరించండి.",
                "fallback_instruction_kn": "ದಯವಿಟ್ಟು ಸ್ಥಳ ಕ್ಷೇತ್ರವನ್ನು ಭರ್ತಿ ಮಾಡಿ.",
                "fallback_instruction_ml": "ദയവായി സ്ഥല ഫീൽഡ് പൂരിപ്പിക്കുക.",
                "fallback_instruction_bn": "দয়া করে অবস্থান ক্ষেত্রটি পূরণ করুন।",
                "fallback_instruction_mr": "कृपया स्थान फील्ड भरा.",
                "fallback_instruction_ur": "براہ کرم مقام کا فیلڈ پُر کریں۔"
            },
            {
                "step_order": 4,
                "screen_name": "Profile Setup",
                "target_id": "profile-story-textarea",
                "gesture_type": "point",
                "instruction_en": "Tell your craft story",
                "instruction_ta": "உங்கள் கைவினை கதையை சொல்லுங்கள்",
                "instruction_hi": "अपनी शिल्प कहानी बताएं",
                "instruction_te": "మీ క్రాఫ్ట్ కథను చెప్పండి",
                "instruction_kn": "ನಿಮ್ಮ ಕರಕುಶಲ ಕಥೆಯನ್ನು ಹೇಳಿ",
                "instruction_ml": "നിങ്ങളുടെ ക്രാഫ്റ്റ് കഥ പറയുക",
                "instruction_bn": "আপনার শিল্পের গল্প বলুন",
                "instruction_mr": "तुमची हस्तकलेची कथा सांगा",
                "instruction_ur": "اپنی دستکاری کی کہانی سنائیں",
                "fallback_instruction_en": "Please fill out your craft story.",
                "fallback_instruction_ta": "உங்கள் கைவினை கதையை நிரப்பவும்.",
                "fallback_instruction_hi": "कृपया अपनी शिल्प कहानी भरें।",
                "fallback_instruction_te": "దయచేసి మీ క్రాఫ్ట్ కథను పూరించండి.",
                "fallback_instruction_kn": "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಕರಕುಶಲ ಕಥೆಯನ್ನು ಭರ್ತಿ ಮಾಡಿ.",
                "fallback_instruction_ml": "ദയവായി നിങ്ങളുടെ ക്രാഫ്റ്റ് കഥ പൂരിപ്പിക്കുക.",
                "fallback_instruction_bn": "দয়া করে আপনার শিল্পের গল্প পূরণ করুন।",
                "fallback_instruction_mr": "कृपया तुमची हस्तकलेची कथा भरा.",
                "fallback_instruction_ur": "براہ کرم اپنی دستکاری کی کہانی پُر کریں۔"
            },
            {
                "step_order": 5,
                "screen_name": "Profile Setup",
                "target_id": "profile-photo-upload",
                "gesture_type": "point",
                "instruction_en": "Add your profile photo",
                "instruction_ta": "உங்கள் சுயவிவரப் புகைப்படத்தைச் சேர்க்கவும்",
                "instruction_hi": "अपनी प्रोफ़ाइल फ़ोटो जोड़ें",
                "instruction_te": "మీ ప్రొఫైల్ ఫోటోను జోడించండి",
                "instruction_kn": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಫೋಟೋ ಸೇರಿಸಿ",
                "instruction_ml": "നിങ്ങളുടെ പ്രൊഫൈൽ ഫോട്ടോ ചേർക്കുക",
                "instruction_bn": "আপনার প্রোফাইল ফটো যোগ করুন",
                "instruction_mr": "तुमचा प्रोफाइल फोटो जोडा",
                "instruction_ur": "اپنی پروفائل تصویر شامل کریں",
                "fallback_instruction_en": "Please upload a profile photo.",
                "fallback_instruction_ta": "சுயவிவரப் புகைப்படத்தைப் பதிவேற்றவும்.",
                "fallback_instruction_hi": "कृपया एक प्रोफ़ाइल फ़ोटो अपलोड करें।",
                "fallback_instruction_te": "దయచేసి ప్రొఫైల్ ఫోటోను అప్‌లోడ్ చేయండి.",
                "fallback_instruction_kn": "ದಯವಿಟ್ಟು ಪ್ರೊಫೈಲ್ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
                "fallback_instruction_ml": "ദയവായി ഒരു പ്രൊഫൈൽ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക.",
                "fallback_instruction_bn": "দয়া করে একটি প্রোফাইল ফটো আপলোড করুন।",
                "fallback_instruction_mr": "कृपया प्रोफाइल फोटो अपलोड करा.",
                "fallback_instruction_ur": "براہ کرم ایک پروفائل تصویر اپ لوڈ کریں۔"
            },
            {
                "step_order": 6,
                "screen_name": "Profile Setup",
                "target_id": "profile-save-button",
                "gesture_type": "point",
                "instruction_en": "Save your profile",
                "instruction_ta": "உங்கள் சுயவிவரத்தை சேமிக்கவும்",
                "instruction_hi": "अपनी प्रोफ़ाइल सहेजें",
                "instruction_te": "మీ ప్రొఫైల్‌ను సేవ్ చేయండి",
                "instruction_kn": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಉಳಿಸಿ",
                "instruction_ml": "നിങ്ങളുടെ പ്രൊഫൈൽ സംരക്ഷിക്കുക",
                "instruction_bn": "আপনার প্রোফাইল সংরক্ষণ করুন",
                "instruction_mr": "तुमचा प्रोफाइल जतन करा",
                "instruction_ur": "اپنی پروفائل محفوظ کریں",
                "fallback_instruction_en": "Click the button to save your profile.",
                "fallback_instruction_ta": "உங்கள் சுயவிவரத்தை சேமிக்க பொத்தானைக் கிளிக் செய்யவும்.",
                "fallback_instruction_hi": "अपनी प्रोफ़ाइल सहेजने के लिए बटन पर क्लिक करें।",
                "fallback_instruction_te": "మీ ప్రొఫైల్‌ను సేవ్ చేయడానికి బటన్‌పై క్లిక్ చేయండి.",
                "fallback_instruction_kn": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಉಳಿಸಲು ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ.",
                "fallback_instruction_ml": "നിങ്ങളുടെ പ്രൊഫൈൽ സംരക്ഷിക്കാൻ ബട്ടണിൽ ക്ലിക്കുചെയ്യുക.",
                "fallback_instruction_bn": "আপনার প্রোফাইল সংরক্ষণ করতে বোতামটিতে ক্লিক করুন।",
                "fallback_instruction_mr": "तुमचा प्रोफाइल जतन करण्यासाठी बटणावर क्लिक करा.",
                "fallback_instruction_ur": "اپنی پروفائل محفوظ کرنے کے لیے بٹن پر کلک کریں۔"
            }
        ]
    },
    {
        "id": "f1c8d2f1-3c2f-4c1e-ac2f-4c1fac2f4c1f",
        "name": "first_product_upload",
        "description": "Guide to uploading your first product",
        "target_role": "artisan",
        "is_active": True,
        "steps": [
            {
                "step_order": 1,
                "screen_name": "Dashboard",
                "target_id": "add-product-button",
                "gesture_type": "tap",
                "instruction_en": "Tap here to add your first product",
                "instruction_ta": "உங்கள் முதல் தயாரிப்பைச் சேர்க்க இங்கே தட்டவும்",
                "instruction_hi": "अपना पहला उत्पाद जोड़ने के लिए यहां टैप करें",
                "instruction_te": "మీ మొదటి ఉత్పత్తిని జోడించడానికి ఇక్కడ నొక్కండి",
                "instruction_kn": "ನಿಮ್ಮ ಮೊದಲ ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಲು ಇಲ್ಲಿ ಟ್ಯಾಪ್ ಮಾಡಿ",
                "instruction_ml": "നിങ്ങളുടെ ആദ്യ ഉൽപ്പന്നം ചേർക്കാൻ ഇവിടെ ടാപ്പുചെയ്യുക",
                "instruction_bn": "আপনার প্রথম পণ্য যোগ করতে এখানে আলতো চাপুন",
                "instruction_mr": "तुमचे पहिले उत्पादन जोडण्यासाठी येथे टॅप करा",
                "instruction_ur": "اپنی پہلی پروڈکٹ شامل کرنے کے لیے یہاں ٹیپ کریں",
                "fallback_instruction_en": "Please click the Add Product button.",
                "fallback_instruction_ta": "தயாரிப்பைச் சேர் பொத்தானைக் கிளிக் செய்யவும்.",
                "fallback_instruction_hi": "कृपया उत्पाद जोड़ें बटन पर क्लिक करें।",
                "fallback_instruction_te": "దయచేసి ఉత్పత్తిని జోడించు బటన్‌పై క్లిక్ చేయండి.",
                "fallback_instruction_kn": "ದಯವಿಟ್ಟು ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಿ ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ.",
                "fallback_instruction_ml": "ദയവായി ഉൽപ്പന്നം ചേർക്കുക ബട്ടണിൽ ക്ലിക്കുചെയ്യുക.",
                "fallback_instruction_bn": "দয়া করে পণ্য যোগ করুন বোতামটিতে ক্লিক করুন।",
                "fallback_instruction_mr": "कृपया उत्पादन जोडा बटणावर क्लिक करा.",
                "fallback_instruction_ur": "براہ کرم پروڈکٹ شامل کریں بٹن پر کلک کریں۔"
            },
            {
                "step_order": 2,
                "screen_name": "Product Step 1",
                "target_id": "add-photo-button",
                "gesture_type": "tap",
                "instruction_en": "Add a clear photo of your product",
                "instruction_ta": "உங்கள் தயாரிப்பின் தெளிவான புகைப்படத்தைச் சேர்க்கவும்",
                "instruction_hi": "अपने उत्पाद की एक स्पष्ट तस्वीर जोड़ें",
                "instruction_te": "మీ ఉత్పత్తి యొక్క స్పష్టమైన ఫోటోను జోడించండి",
                "instruction_kn": "ನಿಮ್ಮ ಉತ್ಪನ್ನದ ಸ್ಪಷ್ಟ ಫೋಟೋವನ್ನು ಸೇರಿಸಿ",
                "instruction_ml": "നിങ്ങളുടെ ഉൽപ്പന്നത്തിന്റെ വ്യക്തമായ ഫോട്ടോ ചേർക്കുക",
                "instruction_bn": "আপনার পণ্যের একটি পরিষ্কার ছবি যোগ করুন",
                "instruction_mr": "तुमच्या उत्पादनाचा स्पष्ट फोटो जोडा",
                "instruction_ur": "اپنی پروڈکٹ کی ایک واضح تصویر شامل کریں",
                "fallback_instruction_en": "Upload a product photo to proceed.",
                "fallback_instruction_ta": "தொடர தயாரிப்பு புகைப்படத்தைப் பதிவேற்றவும்.",
                "fallback_instruction_hi": "आगे बढ़ने के लिए उत्पाद फ़ोटो अपलोड करें।",
                "fallback_instruction_te": "కొనసాగడానికి ఉత్పత్తి ఫోటోను అప్‌లోడ్ చేయండి.",
                "fallback_instruction_kn": "ಮುಂದುವರಿಯಲು ಉತ್ಪನ್ನದ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
                "fallback_instruction_ml": "തുടരുന്നതിന് ഉൽപ്പന്ന ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക.",
                "fallback_instruction_bn": "এগিয়ে যেতে পণ্যের একটি ছবি আপলোড করুন।",
                "fallback_instruction_mr": "पुढे जाण्यासाठी उत्पादनाचा फोटो अपलोड करा.",
                "fallback_instruction_ur": "آگے بڑھنے کے لیے پروڈکٹ کی تصویر اپ لوڈ کریں۔"
            },
            {
                "step_order": 3,
                "screen_name": "Product Step 1 Loading",
                "target_id": "image-processing-loader",
                "gesture_type": "wait",
                "instruction_en": "Please wait, we are improving your photo",
                "instruction_ta": "தயவுசெய்து காத்திருக்கவும், உங்கள் புகைப்படத்தை மேம்படுத்துகிறோம்",
                "instruction_hi": "कृपया प्रतीक्षा करें, हम आपकी फ़ोटो को बेहतर बना रहे हैं",
                "instruction_te": "దయచేసి వేచి ఉండండి, మేము మీ ఫోటోను మెరుగుపరుస్తున్నాము",
                "instruction_kn": "ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ, ನಾವು ನಿಮ್ಮ ಫೋಟೋವನ್ನು ಸುಧಾರಿಸುತ್ತಿದ್ದೇವೆ",
                "instruction_ml": "ദയവായി കാത്തിരിക്കുക, ഞങ്ങൾ നിങ്ങളുടെ ഫോട്ടോ മെച്ചപ്പെടുത്തുകയാണ്",
                "instruction_bn": "অনুগ্রহ করে অপেক্ষা করুন, আমরা আপনার ছবি উন্নত করছি",
                "instruction_mr": "कृपया प्रतीक्षा करा, आम्ही तुमचा फोटो सुधारत आहोत",
                "instruction_ur": "براہ کرم انتظار کریں، ہم آپ کی تصویر کو بہتر بنا رہے ہیں",
                "fallback_instruction_en": "Processing photo...",
                "fallback_instruction_ta": "புகைப்படத்தை செயலாக்குகிறது...",
                "fallback_instruction_hi": "फ़ोटो प्रोसेस हो रही है...",
                "fallback_instruction_te": "ఫోటో ప్రాసెస్ చేయబడుతోంది...",
                "fallback_instruction_kn": "ಫೋಟೋ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
                "fallback_instruction_ml": "ഫോട്ടോ പ്രോസസ്സ് ചെയ്യുന്നു...",
                "fallback_instruction_bn": "ছবি প্রক্রিয়া করা হচ্ছে...",
                "fallback_instruction_mr": "फोटोवर प्रक्रिया होत आहे...",
                "fallback_instruction_ur": "تصویر پر کارروائی ہو رہی ہے..."
            },
            {
                "step_order": 4,
                "screen_name": "Product Step 2 Voice",
                "target_id": "record-voice-button",
                "gesture_type": "tap",
                "instruction_en": "Describe your product in your language",
                "instruction_ta": "உங்கள் தயாரிப்பை உங்கள் மொழியில் விவரிக்கவும்",
                "instruction_hi": "अपनी भाषा में अपने उत्पाद का वर्णन करें",
                "instruction_te": "మీ ఉత్పత్తిని మీ భాషలో వివరించండి",
                "instruction_kn": "ನಿಮ್ಮ ಉತ್ಪನ್ನವನ್ನು ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ವಿವರಿಸಿ",
                "instruction_ml": "നിങ്ങളുടെ ഉൽപ്പന്നത്തെ നിങ്ങളുടെ ഭാഷയിൽ വിവരിക്കുക",
                "instruction_bn": "আপনার ভাষায় আপনার পণ্যের বর্ণনা দিন",
                "instruction_mr": "तुमच्या भाषेत तुमच्या उत्पादनाचे वर्णन करा",
                "instruction_ur": "اپنی زبان میں اپنی پروڈکٹ کی وضاحت کریں",
                "fallback_instruction_en": "Record or type your product description.",
                "fallback_instruction_ta": "உங்கள் தயாரிப்பு விளக்கத்தை பதிவு செய்யவும் அல்லது தட்டச்சு செய்யவும்.",
                "fallback_instruction_hi": "अपने उत्पाद का विवरण रिकॉर्ड करें या टाइप करें।",
                "fallback_instruction_te": "మీ ఉత్పత్తి వివరణను రికార్డ్ చేయండి లేదా టైప్ చేయండి.",
                "fallback_instruction_kn": "ನಿಮ್ಮ ಉತ್ಪನ್ನದ ವಿವರಣೆಯನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಿ ಅಥವಾ ಟೈಪ್ ಮಾಡಿ.",
                "fallback_instruction_ml": "നിങ്ങളുടെ ഉൽപ്പന്ന വിവരണം റെക്കോർഡ് ചെയ്യുക അല്ലെങ്കിൽ ടൈപ്പ് ചെയ്യുക.",
                "fallback_instruction_bn": "আপনার পণ্যের বিবরণ রেকর্ড করুন বা টাইপ করুন।",
                "fallback_instruction_mr": "तुमच्या उत्पादनाचे वर्णन रेकॉर्ड करा किंवा टाइप करा.",
                "fallback_instruction_ur": "اپنی پروڈکٹ کی تفصیل ریکارڈ کریں یا ٹائپ کریں۔"
            },
            {
                "step_order": 5,
                "screen_name": "Product Step 2 Loading",
                "target_id": "ai-processing-loader",
                "gesture_type": "wait",
                "instruction_en": "Creating your product details...",
                "instruction_ta": "உங்கள் தயாரிப்பு விவரங்களை உருவாக்குகிறது...",
                "instruction_hi": "आपके उत्पाद का विवरण बना रहा है...",
                "instruction_te": "మీ ఉత్పత్తి వివరాలను సృష్టిస్తోంది...",
                "instruction_kn": "ನಿಮ್ಮ ಉತ್ಪನ್ನದ ವಿವರಗಳನ್ನು ರಚಿಸಲಾಗುತ್ತಿದೆ...",
                "instruction_ml": "നിങ്ങളുടെ ഉൽപ്പന്ന വിവരങ്ങൾ സൃഷ്ടിക്കുന്നു...",
                "instruction_bn": "আপনার পণ্যের বিবরণ তৈরি করা হচ্ছে...",
                "instruction_mr": "तुमच्या उत्पादनाचे तपशील तयार करत आहे...",
                "instruction_ur": "آپ کی پروڈکٹ کی تفصیلات بنا رہا ہے...",
                "fallback_instruction_en": "Processing details...",
                "fallback_instruction_ta": "விவரங்களை செயலாக்குகிறது...",
                "fallback_instruction_hi": "विवरण प्रोसेस हो रहे हैं...",
                "fallback_instruction_te": "వివరాలను ప్రాసెస్ చేస్తోంది...",
                "fallback_instruction_kn": "ವಿವರಗಳನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
                "fallback_instruction_ml": "വിവരങ്ങൾ പ്രോസസ്സ് ചെയ്യുന്നു...",
                "fallback_instruction_bn": "বিবরণ প্রক্রিয়া করা হচ্ছে...",
                "fallback_instruction_mr": "तपशील प्रक्रिया होत आहे...",
                "fallback_instruction_ur": "تفصیلات پر کارروائی ہو رہی ہے..."
            },
            {
                "step_order": 6,
                "screen_name": "Product Step 3 Review AI",
                "target_id": "review-section",
                "gesture_type": "point",
                "instruction_en": "Check and edit your product details",
                "instruction_ta": "உங்கள் தயாரிப்பு விவரங்களைச் சரிபார்த்து திருத்தவும்",
                "instruction_hi": "अपने उत्पाद विवरण की जाँच करें और संपादित करें",
                "instruction_te": "మీ ఉత్పత్తి వివరాలను తనిఖీ చేయండి మరియు సవరించండి",
                "instruction_kn": "ನಿಮ್ಮ ಉತ್ಪನ್ನದ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸಂಪಾದಿಸಿ",
                "instruction_ml": "നിങ്ങളുടെ ഉൽപ്പന്ന വിവരങ്ങൾ പരിശോധിക്കുകയും തിരുത്തുകയും ചെയ്യുക",
                "instruction_bn": "আপনার পণ্যের বিবরণ পরীক্ষা করুন এবং সম্পাদনা করুন",
                "instruction_mr": "तुमच्या उत्पादनाचे तपशील तपासा आणि संपादित करा",
                "instruction_ur": "اپنی پروڈکٹ کی تفصیلات چیک کریں اور ان میں ترمیم کریں",
                "fallback_instruction_en": "Please review your product details.",
                "fallback_instruction_ta": "உங்கள் தயாரிப்பு விவரங்களை மதிப்பாய்வு செய்யவும்.",
                "fallback_instruction_hi": "कृपया अपने उत्पाद विवरण की समीक्षा करें।",
                "fallback_instruction_te": "దయచేసి మీ ఉత్పత్తి వివరాలను సమీక్షించండి.",
                "fallback_instruction_kn": "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಉತ್ಪನ್ನದ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
                "fallback_instruction_ml": "ദയവായി നിങ്ങളുടെ ഉൽപ്പന്ന വിവരങ്ങൾ അവലോകനം ചെയ്യുക.",
                "fallback_instruction_bn": "দয়া করে আপনার পণ্যের বিবরণ পর্যালোচনা করুন।",
                "fallback_instruction_mr": "कृपया तुमच्या उत्पादनाच्या तपशीलांचे पुनरावलोकन करा.",
                "fallback_instruction_ur": "براہ کرم اپنی پروڈکٹ کی تفصیلات کا جائزہ لیں۔"
            },
            {
                "step_order": 7,
                "screen_name": "Product Step 4 Materials",
                "target_id": "material-checklist",
                "gesture_type": "point",
                "instruction_en": "Confirm your materials and costs",
                "instruction_ta": "உங்கள் பொருட்கள் மற்றும் செலவுகளை உறுதிப்படுத்தவும்",
                "instruction_hi": "अपनी सामग्री और लागत की पुष्टि करें",
                "instruction_te": "మీ పదార్థాలు మరియు ఖర్చులను నిర్ధారించండి",
                "instruction_kn": "ನಿಮ್ಮ ಸಾಮಗ್ರಿಗಳು ಮತ್ತು ವೆಚ್ಚಗಳನ್ನು ದೃಢೀಕರಿಸಿ",
                "instruction_ml": "നിങ്ങളുടെ വസ്തുക്കളും ചെലവുകളും സ്ഥിരീകരിക്കുക",
                "instruction_bn": "আপনার উপকরণ এবং খরচ নিশ্চিত করুন",
                "instruction_mr": "तुमची सामग्री आणि खर्चाची पुष्टी करा",
                "instruction_ur": "اپنے مواد اور اخراجات کی تصدیق کریں",
                "fallback_instruction_en": "Review the materials list.",
                "fallback_instruction_ta": "பொருட்கள் பட்டியலை மதிப்பாய்வு செய்யவும்.",
                "fallback_instruction_hi": "सामग्री सूची की समीक्षा करें।",
                "fallback_instruction_te": "పదార్థాల జాబితాను సమీక్షించండి.",
                "fallback_instruction_kn": "ಸಾಮಗ್ರಿಗಳ ಪಟ್ಟಿಯನ್ನು ಪರಿಶೀಲಿಸಿ.",
                "fallback_instruction_ml": "വസ്തുക്കളുടെ ലിസ്റ്റ് അവലോകനം ചെയ്യുക.",
                "fallback_instruction_bn": "উপকরণের তালিকাটি পর্যালোচনা করুন।",
                "fallback_instruction_mr": "सामग्री सूचीचे पुनरावलोकन करा.",
                "fallback_instruction_ur": "مواد کی فہرست کا جائزہ لیں۔"
            },
            {
                "step_order": 8,
                "screen_name": "Product Step 5 Pricing",
                "target_id": "fair-price-section",
                "gesture_type": "point",
                "instruction_en": "Set a fair price for your product",
                "instruction_ta": "உங்கள் தயாரிப்புக்கு நியாயமான விலையை நிர்ணயிக்கவும்",
                "instruction_hi": "अपने उत्पाद के लिए एक उचित मूल्य निर्धारित करें",
                "instruction_te": "మీ ఉత్పత్తికి సరసమైన ధరను నిర్ణయించండి",
                "instruction_kn": "ನಿಮ್ಮ ಉತ್ಪನ್ನಕ್ಕೆ ನ್ಯಾಯಯುತ ಬೆಲೆಯನ್ನು ನಿಗದಿಪಡಿಸಿ",
                "instruction_ml": "നിങ്ങളുടെ ഉൽപ്പന്നത്തിന് ന്യായമായ വില നിശ്ചയിക്കുക",
                "instruction_bn": "আপনার পণ্যের জন্য একটি ন্যায্য মূল্য নির্ধারণ করুন",
                "instruction_mr": "तुमच्या उत्पादनासाठी योग्य किंमत सेट करा",
                "instruction_ur": "اپنی پروڈکٹ کے لیے مناسب قیمت مقرر کریں",
                "fallback_instruction_en": "Set your final product price.",
                "fallback_instruction_ta": "உங்கள் இறுதி தயாரிப்பு விலையை அமைக்கவும்.",
                "fallback_instruction_hi": "अपना अंतिम उत्पाद मूल्य निर्धारित करें।",
                "fallback_instruction_te": "మీ తుది ఉత్పత్తి ధరను సెట్ చేయండి.",
                "fallback_instruction_kn": "ನಿಮ್ಮ ಅಂತಿಮ ಉತ್ಪನ್ನದ ಬೆಲೆಯನ್ನು ಹೊಂದಿಸಿ.",
                "fallback_instruction_ml": "നിങ്ങളുടെ അവസാന ഉൽപ്പന്ന വില സജ്ജമാക്കുക.",
                "fallback_instruction_bn": "আপনার চূড়ান্ত পণ্যের মূল্য নির্ধারণ করুন।",
                "fallback_instruction_mr": "तुमची अंतिम उत्पादनाची किंमत सेट करा.",
                "fallback_instruction_ur": "اپنی حتمی پروڈکٹ کی قیمت مقرر کریں۔"
            },
            {
                "step_order": 9,
                "screen_name": "Product Step 6 Publish",
                "target_id": "readiness-score",
                "gesture_type": "point",
                "instruction_en": "Check if your listing is complete",
                "instruction_ta": "உங்கள் பட்டியல் முழுமையாக உள்ளதா எனச் சரிபார்க்கவும்",
                "instruction_hi": "जांचें कि क्या आपकी लिस्टिंग पूरी हो गई है",
                "instruction_te": "మీ జాబితా పూర్తయిందో లేదో తనిఖీ చేయండి",
                "instruction_kn": "ನಿಮ್ಮ ಪಟ್ಟಿ ಪೂರ್ಣಗೊಂಡಿದೆಯೇ ಎಂದು ಪರಿಶೀಲಿಸಿ",
                "instruction_ml": "നിങ്ങളുടെ ലിസ്റ്റിംഗ് പൂർണ്ണമാണോ എന്ന് പരിശോധിക്കുക",
                "instruction_bn": "আপনার তালিকাটি সম্পূর্ণ হয়েছে কিনা তা পরীক্ষা করুন",
                "instruction_mr": "तुमची सूची पूर्ण झाली आहे का ते तपासा",
                "instruction_ur": "چیک کریں کہ آیا آپ کی فہرست مکمل ہے",
                "fallback_instruction_en": "Review your readiness score.",
                "fallback_instruction_ta": "உங்கள் தயார்நிலை மதிப்பெண்ணை மதிப்பாய்வு செய்யவும்.",
                "fallback_instruction_hi": "अपने तत्परता स्कोर की समीक्षा करें।",
                "fallback_instruction_te": "మీ సంసిద్ధత స్కోర్‌ను సమీక్షించండి.",
                "fallback_instruction_kn": "ನಿಮ್ಮ ಸಿದ್ಧತೆ ಸ್ಕೋರ್ ಅನ್ನು ಪರಿಶೀಲಿಸಿ.",
                "fallback_instruction_ml": "നിങ്ങളുടെ തയ്യാറെടുപ്പ് സ്കോർ അവലോകനം ചെയ്യുക.",
                "fallback_instruction_bn": "আপনার প্রস্তুতির স্কোর পর্যালোচনা করুন।",
                "fallback_instruction_mr": "तुमच्या तयारीच्या स्कोअरचे पुनरावलोकन करा.",
                "fallback_instruction_ur": "اپنی تیاری کے اسکور کا جائزہ لیں۔"
            },
            {
                "step_order": 10,
                "screen_name": "Product Step 6 Publish",
                "target_id": "publish-button",
                "gesture_type": "tap",
                "instruction_en": "Publish your product for buyers",
                "instruction_ta": "வாங்குபவர்களுக்காக உங்கள் தயாரிப்பை வெளியிடவும்",
                "instruction_hi": "खरीदारों के लिए अपना उत्पाद प्रकाशित करें",
                "instruction_te": "కొనుగోలుదారుల కోసం మీ ఉత్పత్తిని ప్రచురించండి",
                "instruction_kn": "ಖರೀದಿದಾರರಿಗಾಗಿ ನಿಮ್ಮ ಉತ್ಪನ್ನವನ್ನು ಪ್ರಕಟಿಸಿ",
                "instruction_ml": "വാങ്ങുന്നവർക്കായി നിങ്ങളുടെ ഉൽപ്പന്നം പ്രസിദ്ധീകരിക്കുക",
                "instruction_bn": "ক্রেতাদের জন্য আপনার পণ্য প্রকাশ করুন",
                "instruction_mr": "खरेदीदारांसाठी तुमचे उत्पादन प्रकाशित करा",
                "instruction_ur": "خریداروں کے لیے اپنی پروڈکٹ شائع کریں",
                "fallback_instruction_en": "Click publish to finish.",
                "fallback_instruction_ta": "முடிக்க வெளியிடு என்பதைக் கிளிக் செய்யவும்.",
                "fallback_instruction_hi": "समाप्त करने के लिए प्रकाशित करें पर क्लिक करें।",
                "fallback_instruction_te": "పూర్తి చేయడానికి ప్రచురించుపై క్లిక్ చేయండి.",
                "fallback_instruction_kn": "ಮುಗಿಸಲು ಪ್ರಕಟಿಸು ಕ್ಲಿಕ್ ಮಾಡಿ.",
                "fallback_instruction_ml": "പൂർത്തിയാക്കാൻ പ്രസിദ്ധീകരിക്കുക ക്ലിക്കുചെയ്യുക.",
                "fallback_instruction_bn": "শেষ করতে প্রকাশ করুন এ ক্লিক করুন।",
                "fallback_instruction_mr": "पूर्ण करण्यासाठी प्रकाशित करा वर क्लिक करा.",
                "fallback_instruction_ur": "ختم کرنے کے لیے شائع کریں پر کلک کریں۔"
            }
        ]
    },
    {
        "id": "e3a1b2c4-5d6e-7f8g-9h0i-1j2k3l4m5n6o",
        "name": "enquiry_response",
        "description": "Guide to responding to a buyer enquiry",
        "target_role": "artisan",
        "is_active": True,
        "steps": [
            {
                "step_order": 1,
                "screen_name": "Enquiry List",
                "target_id": "enquiry-list",
                "gesture_type": "point",
                "instruction_en": "A buyer is interested in your product",
                "instruction_ta": "ஒரு வாங்குபவர் உங்கள் தயாரிப்பில் ஆர்வம் காட்டுகிறார்",
                "instruction_hi": "एक खरीदार आपके उत्पाद में रुचि रखता है",
                "instruction_te": "కొనుగోలుదారు మీ ఉత్పత్తిపై ఆసక్తి చూపుతున్నాడు",
                "instruction_kn": "ಖರೀದಿದಾರರು ನಿಮ್ಮ ಉತ್ಪನ್ನದಲ್ಲಿ ಆಸಕ್ತಿ ಹೊಂದಿದ್ದಾರೆ",
                "instruction_ml": "ഒരു വാങ്ങലുകാരൻ നിങ്ങളുടെ ഉൽപ്പന്നത്തിൽ താൽപ്പര്യം പ്രകടിപ്പിക്കുന്നു",
                "instruction_bn": "একজন ক্রেতা আপনার পণ্যে আগ্রহী",
                "instruction_mr": "एक खरेदीदार तुमच्या उत्पादनात स्वारस्य दाखवत आहे",
                "instruction_ur": "ایک خریدار آپ کی پروڈکٹ میں دلچسپی رکھتا ہے",
                "fallback_instruction_en": "You have a new enquiry.",
                "fallback_instruction_ta": "உங்களுக்கு ஒரு புதிய விசாரணை உள்ளது.",
                "fallback_instruction_hi": "आपके पास एक नई पूछताछ है।",
                "fallback_instruction_te": "మీకు కొత్త విచారణ ఉంది.",
                "fallback_instruction_kn": "ನೀವು ಹೊಸ ವಿಚಾರಣೆಯನ್ನು ಹೊಂದಿದ್ದೀರಿ.",
                "fallback_instruction_ml": "നിങ്ങൾക്ക് ഒരു പുതിയ അന്വേഷണമുണ്ട്.",
                "fallback_instruction_bn": "আপনার একটি নতুন অনুসন্ধান আছে।",
                "fallback_instruction_mr": "तुमच्याकडे नवीन चौकशी आहे.",
                "fallback_instruction_ur": "آپ کے پاس ایک نئی انکوائری ہے۔"
            },
            {
                "step_order": 2,
                "screen_name": "Enquiry Detail",
                "target_id": "enquiry-detail",
                "gesture_type": "point",
                "instruction_en": "Review the buyer's request",
                "instruction_ta": "வாங்குபவரின் கோரிக்கையை மதிப்பாய்வு செய்யவும்",
                "instruction_hi": "खरीदार के अनुरोध की समीक्षा करें",
                "instruction_te": "కొనుగోలుదారు అభ్యర్థనను సమీక్షించండి",
                "instruction_kn": "ಖರೀದಿದಾರರ ವಿನಂತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ",
                "instruction_ml": "വാങ്ങുന്നയാളുടെ അഭ്യർത്ഥന അവലോകനം ചെയ്യുക",
                "instruction_bn": "ক্রেতার অনুরোধ পর্যালোচনা করুন",
                "instruction_mr": "खरेदीदाराच्या विनंतीचे पुनरावलोकन करा",
                "instruction_ur": "خریدار کی درخواست کا جائزہ لیں",
                "fallback_instruction_en": "Check the details of the enquiry.",
                "fallback_instruction_ta": "விசாரணையின் விவரங்களைச் சரிபார்க்கவும்.",
                "fallback_instruction_hi": "पूछताछ के विवरण की जांच करें।",
                "fallback_instruction_te": "విచారణ వివరాలను తనిఖీ చేయండి.",
                "fallback_instruction_kn": "ವಿಚಾರಣೆಯ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
                "fallback_instruction_ml": "അന്വേഷണത്തിന്റെ വിശദാംശങ്ങൾ പരിശോധിക്കുക.",
                "fallback_instruction_bn": "অনুসন্ধানের বিবরণ পরীক্ষা করুন।",
                "fallback_instruction_mr": "चौकशीचे तपशील तपासा.",
                "fallback_instruction_ur": "انکوائری کی تفصیلات چیک کریں۔"
            },
            {
                "step_order": 3,
                "screen_name": "Enquiry Detail",
                "target_id": "response-options",
                "gesture_type": "point",
                "instruction_en": "Choose your response",
                "instruction_ta": "உங்கள் பதிலை தேர்வு செய்யவும்",
                "instruction_hi": "अपनी प्रतिक्रिया चुनें",
                "instruction_te": "మీ ప్రతిస్పందనను ఎంచుకోండి",
                "instruction_kn": "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಆರಿಸಿ",
                "instruction_ml": "നിങ്ങളുടെ പ്രതികരണം തിരഞ്ഞെടുക്കുക",
                "instruction_bn": "আপনার প্রতিক্রিয়া চয়ন করুন",
                "instruction_mr": "तुमचा प्रतिसाद निवडा",
                "instruction_ur": "اپنا جواب منتخب کریں",
                "fallback_instruction_en": "Select how you want to respond.",
                "fallback_instruction_ta": "நீங்கள் எவ்வாறு பதிலளிக்க விரும்புகிறீர்கள் என்பதைத் தேர்ந்தெடுக்கவும்.",
                "fallback_instruction_hi": "चुनें कि आप कैसे प्रतिक्रिया देना चाहते हैं।",
                "fallback_instruction_te": "మీరు ఎలా ప్రతిస్పందించాలనుకుంటున్నారో ఎంచుకోండి.",
                "fallback_instruction_kn": "ನೀವು ಹೇಗೆ ಪ್ರತಿಕ್ರಿಯಿಸಲು ಬಯಸುತ್ತೀರಿ ಎಂಬುದನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
                "fallback_instruction_ml": "നിങ്ങൾ എങ്ങനെ പ്രതികരിക്കണമെന്ന് തിരഞ്ഞെടുക്കുക.",
                "fallback_instruction_bn": "আপনি কীভাবে সাড়া দিতে চান তা নির্বাচন করুন।",
                "fallback_instruction_mr": "तुम्हाला कसा प्रतिसाद द्यायचा आहे ते निवडा.",
                "fallback_instruction_ur": "منتخب کریں کہ آپ کیسے جواب دینا چاہتے ہیں۔"
            },
            {
                "step_order": 4,
                "screen_name": "Enquiry Detail",
                "target_id": "send-response-button",
                "gesture_type": "tap",
                "instruction_en": "Send your response to the buyer",
                "instruction_ta": "வாங்குபவருக்கு உங்கள் பதிலை அனுப்பவும்",
                "instruction_hi": "खरीदार को अपनी प्रतिक्रिया भेजें",
                "instruction_te": "కొనుగోలుదారుకు మీ ప్రతిస్పందనను పంపండి",
                "instruction_kn": "ಖರೀದಿದಾರರಿಗೆ ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಕಳುಹಿಸಿ",
                "instruction_ml": "വാങ്ങുന്നയാൾക്ക് നിങ്ങളുടെ പ്രതികരണം അയയ്ക്കുക",
                "instruction_bn": "ক্রেতার কাছে আপনার প্রতিক্রিয়া পাঠান",
                "instruction_mr": "खरेदीदाराला तुमचा प्रतिसाद पाठवा",
                "instruction_ur": "خریدار کو اپنا جواب بھیجیں",
                "fallback_instruction_en": "Click here to send.",
                "fallback_instruction_ta": "அனுப்ப இங்கே கிளிக் செய்யவும்.",
                "fallback_instruction_hi": "भेजने के लिए यहां क्लिक करें।",
                "fallback_instruction_te": "పంపడానికి ఇక్కడ క్లిక్ చేయండి.",
                "fallback_instruction_kn": "ಕಳುಹಿಸಲು ಇಲ್ಲಿ ಕ್ಲಿಕ್ ಮಾಡಿ.",
                "fallback_instruction_ml": "അയയ്ക്കാൻ ഇവിടെ ക്ലിക്കുചെയ്യുക.",
                "fallback_instruction_bn": "পাঠাতে এখানে ক্লিক করুন।",
                "fallback_instruction_mr": "पाठवण्यासाठी येथे क्लिक करा.",
                "fallback_instruction_ur": "بھیجنے کے لیے یہاں کلک کریں۔"
            }
        ]
    }
]
